### ISSUE TITLE
Question: is there a way to create virtual files? (like a procfs)

### ISSUE THREAD

**Issue by psantosl** [microsoft/ProjFS-Managed-API#46]
Hi,

Can virtual files be created with profjs?

I mean, suppose you want to create something like a directory to show info of running processes. Possible?

If not: expected?

I understand the basic functionality of procfs and I love it, but I'd like to have both "copied files" and virtual files.

Thanks!

**Comment by cgallred** [comment]
Yes, you could do something like procfs with ProjFS. Your provider application would get the process info and surface it as directories and files. When process info changes the provider would use the [PrjDeleteFile](https://docs.microsoft.com/en-us/windows/win32/api/projectedfslib/nf-projectedfslib-prjdeletefile)/[PrjUpdateFileIfNeeded](https://docs.microsoft.com/en-us/windows/win32/api/projectedfslib/nf-projectedfslib-prjupdatefileifneeded) APIs to update anything that had been cached to the disk due to user access. See [Handling View Changes](https://docs.microsoft.com/en-us/windows/win32/projfs/handling-view-changes) for more information.
