### ISSUE TITLE
After closing SimpleProviderManager artifacts are left behind in the virtual root

### ISSUE THREAD

**Issue by jhv2017kam** [microsoft/ProjFS-Managed-API#60]
After closing SimpleProviderManager the virtual root still contains the file names that was previously provided
these names even survive a restart

content can still be read, 
still visible in windows explorer and by cmd dir
but attempt to modify with notepad++ you get an error and afterward they are gone

**Comment by cgallred** [comment]
That is expected behavior. The first time you create a handle to a projected file, a placeholder for the file is created on your disk. The first time you read from the file, its contents are written to disk. So stopping the provider application will leave behind those files and their contents. ProjFS prevents modifications to files that haven't previously been written to, and for certain scenarios will remove them from the disk.

See [this documentation](https://docs.microsoft.com/en-us/windows/win32/projfs/provider-overview#data-projection) on how data is projected, and this page on [cache state in the virtualization root](https://docs.microsoft.com/en-us/windows/win32/projfs/cache-state).
